### ISSUE TITLE
ETEO Algorithm logical issues

### ISSUE THREAD

**Issue by DeepAnonymous** [TradeMaster-NTU/TradeMaster#118]
Hi,

I haven't still got the whole idea of ETEO implementation, so I create this new thread. Hope you guys can discuss and give some comments.

1.  Some conditional statement regarding `if order[1] == self.data["midpoint"] ... * 0.01` almost never happens. Because the predicted price order[1] rarely satisfy this condition. I'm wondering why you didn't use `<=` or `>=` instead of `==` 
2. What is the meaning behind `start_volume`, because you calculate `start_volume`, and assign it to `order` then `order_history`, and use it to calculate `tradable_volume`, but then again, the condition `if order[1] == self.data["midpoint"] ... * 0.01` rarely happen.
3. Also, should I modify `buy_volume = min(action[0], **self.state[-1]**)`, because buy volume should not larger than order left.
4. Somehow, I find duplicating check action and order is little weird (with the same conditional)
5. Currently, action[0] is always positive, which mean we are going to **buy** more bitcoin. Do we need to train another model to **sell**? I don't think 1 AI model can handle 2 buy & sell tasks.

I am looking forward to your discussion.
Thank you.

**Comment by qinmoelei** [comment]
Hi

> Some conditional statement regarding` if order[1] == self.data["midpoint"] ... * 0.01` almost never happens. Because the predicted price order[1] rarely satisfy this condition. I'm wondering why you didn't use `<= `or `>= `instead of `==`
> What is the meaning behind `start_volume`, because you calculate` start_volume`, and assign it to order then `order_history`, and use it to calculate `tradable_volume`, but then again, the condition `if order[1] == self.data["midpoint"] ... * 0.01` rarely happen.

These 2 questions can be answered together by explaining the stepping process.
After you place an order, based on the price and volume, we will check whether this order could be executed right away, if so, we executed this order and add an order in order  history with volume 0 to take up this timestamp, if not, then the unexecuted order still will be saved in the order history.
The order history's elements (unexecuted order) have 3 dimensions (volume,price,start_volume), the volume and price are referring the order we remained. The start_volume indicates the how many orders are in front of you with **exactly the same price**, which means that if your order is not exactly the same as the order book, then it will create a new level, where your order will be executed first in this level. However, things are a little different if your price is exactly the same as others, you have to calculate how many orders are in front of your order. For example, if you place a bid order with 1 BTC at 20001 USD, when the current ask price is 20002, but there are already 2BTC bid orders at 20001 USD in front of you and no order is behind you, none of these orders are executed at this moment, however, at the next timestamp, the LOB ask price becomes 20002 USD, with 0.001 BTC order. At this moment, you can't say our order has been executed, because the left ask order is only 0.001BTC after taking up the previous 2BTC and you order can only be executed 0.001BTC

> Also, should I modify` buy_volume = min(action[0], **self.state[-1]**)`, because buy volume should not larger than order left.

A more decent way is to add this to the agents instead of the environment. Adding this to environment will mask some information to the agent and is not good for learning.
> Somehow, I find duplicating check action and order is little weird (with the same conditional)

We will modify the environments in the future.

> Currently, action[0] is always positive, which mean we are going to buy more bitcoin. Do we need to train another model to sell? I don't think 1 AI model can handle 2 buy & sell tasks.

Yes, if you want to do order execution in 2 ways, I think you should train 2 models.

Hope this can help you.

**Comment by sunshuo01** [comment]
Hi,

I actually agree with you that the current version of order execution is too completed with some weird details. We would like to improve it but we are currently busy with some other features. You are welcomed to help us improve it if possible. Thank you for your sincere interest on TradeMaster.

**Comment by DeepAnonymous** [comment]
Thank you very much for your responses, especially the **start_volume** part. 

I find this project really interesting and helpful thanks to you guys. I hope I could pull some requests sometime.

Have a good day!

**Comment by DeepAnonymous** [comment]
I asked about start_volume because I was confused due to *** 0.01** calculation. 

Anyway, I believe there is a **missing * 0.01** at line #180.

Btw, can I use `self.data["midpoint"] + self.data["bids_distance_{}".format(i)]` instead of `
self.data["midpoint"] * (1 + self.data["bids_distance_{}".format(i)] * 0.01)`

**Comment by qinmoelei** [comment]
Thanks for your feed back.
You also right about the meaning of distance, I wrongly use this value to recover the orginal LOB. 
We will fix it soon.
Have a good day!
