### ISSUE TITLE
KeyError: 'PortfolioManagementEIIETrainer is not in the trainer registry'

### ISSUE THREAD

**Issue by circle2nd** [TradeMaster-NTU/TradeMaster#135]
刚开始运行Tutorial1_EIIE，在运行下面代码时出现报错：
trainer = build_trainer(cfg, default_args=dict(train_environment=train_environment,valid_environment=valid_environment,test_environment=test_environment,agent=agent,device=device))
work_dir = os.path.join(ROOT, cfg.trainer.work_dir)

if not os.path.exists(work_dir):
os.makedirs(work_dir)
cfg.dump(osp.join(work_dir, osp.basename(args.config)))

报错：KeyError: 'PortfolioManagementEIIETrainer is not in the trainer registry'
KeyError                                  Traceback (most recent call last)
Input In [19], in <cell line: 1>()
----> 1 trainer = build_trainer(cfg, default_args=dict(train_environment=train_environment,valid_environment=valid_environment,test_environment=test_environment,agent=agent,device=device))
      2 work_dir = os.path.join(ROOT, cfg.trainer.work_dir)
      4 if not os.path.exists(work_dir):

File D:\0quant_nft_nlp\model_quant_qlib\TradeMaster\TradeMaster-1.0.0\trademaster\trainers\builder.py:8, in build_trainer(cfg, default_args)
      6 def build_trainer(cfg, default_args=None):
      7     cp_cfg = dict(cfg.trainer)
----> 8     trainer = build_from_cfg(cp_cfg, TRAINERS, default_args)
      9     return trainer

File D:\0quant_nft_nlp\model_quant_qlib\TradeMaster\TradeMaster-1.0.0\trademaster\utils\utils.py:107, in build_from_cfg(cfg, registry, default_args)
    105     obj_cls = registry.get(obj_type)
    106     if obj_cls is None:
--> 107         raise KeyError(
    108             f'{obj_type} is not in the {registry.name} registry')
    109 elif inspect.isclass(obj_type):
    110     obj_cls = obj_type

KeyError: 'PortfolioManagementEIIETrainer is not in the trainer registry'

请教怎么解决，谢谢。

**Comment by DVampire** [comment]
ray occasionally has this Trainer not registering in the notebook, but we have not located what the problem is. Perhaps you could refer to the python script https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/tools/portfolio_management/train_eiie.py which is the same function as the notebook . Finally, hopefully we can communicate in English so that everyone can read it. Thank you for your interest

Translated with www.DeepL.com/Translator (free version)

**Comment by DVampire** [comment]
ray occasionally has this Trainer not registering in the notebook, but we have not located what the problem is. Perhaps you could refer to the python script https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/tools/portfolio_management/train_eiie.py which is the same function as the notebook . Finally, hopefully we can communicate in English so that everyone can read it. Thank you for your interest

**Comment by circle2nd** [comment]
Thanks a lot.
