### ISSUE TITLE
Questions about the implementation of DeepScalper

### ISSUE THREAD

**Issue by ZhangYou0122** [TradeMaster-NTU/TradeMaster#150]
Hi, first I'd like to thank you all for this brilliant repo!

I found this repo by searching the relevant information of DeepScalper. I see this repo is maintained by a team of NTU led by Prof Bo An, who is also one of the authors of DeepScalper, so it's reasonable to assume that what is implemented here should be the same as what is described in the paper. However, I have found some major discrepancies:
1. The paper says DeepScalper uses both macro-level(OHLCV data and technical indicators) and micro-level(LOB data) as features, but in this repo only macro-level data is used.
2. The paper uses per-minute OHLCV data, while this repo only uses daily OHLCV data.
3. The paper states that a two-dimensional action space of (price, volume) is used: 
> We use a more realistic two-dimensional
> fine-grained action space for intraday trading, which represents
> a limit order as a tuple (𝑝𝑡𝑎𝑟𝑔𝑒𝑡, ±𝑞𝑡𝑎𝑟𝑔𝑒𝑡). 𝑝𝑡𝑎𝑟𝑔𝑒𝑡 is the target
> price, 𝑞𝑡𝑎𝑟𝑔𝑒𝑡 is the target quantity and ± is the trading direction
> (long/short).

However, in this repo only the volume dimension is present, and the execution price is simply assumed to be the latest trade price(close price) of the last bar, which is not a realistic assumption in the context of high frequency trading, as it ignores bid-ask spread and slippage.

All the above makes the implementation looks like only a prototype instead of a real one. I wonder what is the reason behind it? Your reply would be appreciated, thanks!

**Comment by joshwigginton** [comment]
Have you reviewed the DDQN High Frequency Trading Jupyter notebook and/or configs? They are using LOB data and the same DDQN agent.  

https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/tutorial/Tutorial6_DDQN.ipynb

**Comment by sunshuo01** [comment]
Thanks for your interest :blush:! As you mentioned, the implementation of DeepScalper is a prototype version. The reason is that the original code is built based on the codebase and minute-level stock index and treasury bond data provided by our industry collaborators, which is not allowed to make them publicly available due to confidentiality requirement. While building this TradeMaster repo, our first priority is to build the whole RL for trading pipeline. So we decide to implement this prototype version first.

If you are interested in DeepScalper, we are more than happy to help you make a pull request for the full version of DeepScalper on this TradeMaster repo.

If you are interested in trading with the more realistic two-dimensional actions, we would like to recommend the current high frequency trading settings in this repo as @joshwigginton suggests.

Our team will continuously update this repo to improve its quality in the future. Could you please star and fork this repo to avoid missing new updates? Your support means a lot to us. Thank you.

**Comment by ZhangYou0122** [comment]
I understand that the LOB/minute-level data should remain confidential because they are provided by industry collaborators, however, it seems a bit strange that the codebase(especially the RL part) is also provided by them and cannot be disclosed.

Anyway, thanks for building this great repo again! I have starred this repo and will also check the hft settings.

**Comment by sunshuo01** [comment]
For the codebase, it is provided by our collaborators because it is implemented based on the company's previous internal code on some other RL for trading projects. I agree that it is possible to disclose the key RL part with some other open-source minute-level LOB and k-line data. However, there are many difficulties in practice. For instance, the performance variability of RL across different datasets is usually large so that we need to tune all knobs such as hyperparameters again. The original one and TradeMaster are built on different RL frameworks so that it takes engineering efforts to transfer the implementation.

Even though there are some difficulties, I agree with you that this is a good feature to be added. We will work on this later and hopefully it can be available by the end of next month . Thanks again for your interest !

**Comment by ZhangYou0122** [comment]
That's great to hear! I'm very grateful for your commitment and your patience. Yes, I can imagine that it is not a trivial task to migrate the legacy code to a new framework and on a new dataset, which makes your committment on it even more precious. I'm looking forward for this new feature!

**Comment by ZhangYou0122** [comment]
Hello! It's been a while, I wonder is there any updates on DeepScapler?
