### ISSUE TITLE
tools/market_dynamics_labeling/run.py not taking in command line config arguments

### ISSUE THREAD

**Issue by joshwigginton** [TradeMaster-NTU/TradeMaster#151]
The run.py script does not take in the command line arguments, but only reads the values from configs/evaluation/market_dynamics_modeling.py file. 

Example: 
python tools/market_dynamics_labeling/run.py --data_path  data/portfolio_management/dj30/DJI.csv --method linear --fitting_parameters 2/7 2/14 4 --labeling_parameters -0.25 0.25  --regime_number 3 --length
_limit 24  --PM data/portfolio_management/dj30/test.csv

I added print statement to run.py to print the cfgs passed to build_market_dynamics_model:
model = build_market_dynamics_model(cfg)

this is cfgs values:
Config (path: /home/TradeMaster/configs/evaluation/market_dynamics_modeling.py): {'market_dynamics_model': {'data_path': 'data/high_frequency_trading/small_BTC/test.csv', 'fitting_parameters': ['2/7', '2/14', '4'], 'labeling_parameters': [-0.01, 0.01], 'regime_number': 3, 'length_limit': 300, 'OE_BTC': False, 'PM': '', 'process_datafile_path': '/home/TradeMaster/data/high_frequency_trading/small_BTC/test_labeled_3_300_-0.01_0.01.csv', 'market_dynamic_labeling_visualization_paths': ['/home/TradeMaster/data/high_frequency_trading/small_BTC/MDM_linear/3_300_-0.01_0.01_HFT_small_BTC.png'], 'type': 'Linear_Market_Dynamics_Model'}, 'task_name': 'algorithmic_trading', 'dataset_name': 'BTC'}

**Comment by XiaHaochong98** [comment]
Sorry for the confusion.

As stated in the doc (https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/docs/source/tool/EvaluationSandbox_MDM.md), you may either run the tool from command line **or**  configuration file but not at the same time.

The recommendation is to run the tool  configuration file. You may directly change the parameters in the configuration file instead of using the command line to control it. We believe using the configuration file will keep everything clean and smooth when you are running experiments.

Hope this answers your question, thank you for your interest  in TradeMaster
