### ISSUE TITLE
Can trademaster train using tick data?

### ISSUE THREAD

**Issue by ztwe** [TradeMaster-NTU/TradeMaster#152]
Can trademaster train using tick data?

If not, how to modify the project?

**Comment by sunshuo01** [comment]
Thanks for your interest on TradeMaster. May I ask what is the data structure of the tick data we want to train? What trading tasks are you working on?

**Comment by ztwe** [comment]
The data structure is like bid_5/bid_4/bid_3/bid_2/bid_1、ask_1/ask_2/ask_3/ask_4/ask_5, both for price and order. The training is about chinese future.

**Comment by sunshuo01** [comment]
You may take a look at this tutorial https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/tutorial/Tutorial6_DDQN.ipynb. I think it is using data with similar structures on Crypto trading.

**Comment by ztwe** [comment]
Besides data structure, could the environment support the trade which less than 1min, like buy and then sell within 1min.

**Comment by ztwe** [comment]
In addition, could the models and environment  accept tick data(...bid_2/bid_1、ask_1/ask_2/...) and OHLCV data simultaneously?

**Comment by sunshuo01** [comment]
As far as I know, the current version is using technical indicators for states. I think it is possible to modify it to accept tick and OHLCV together. But intuitively, this may not be a very good way because it can be hard to train RL agents with good results using only raw tick and OHLCV  data based on my previous experience.

**Comment by ztwe** [comment]
Thank you!
