### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by joshwigginton** [TradeMaster-NTU/TradeMaster#157]
First of all - thank you so much for the project. Your code, organization and documentation are excellent. It's great to find a project that works and examples / notebooks are helpful and work well. Thank you again. I love reading your papers also, very informative. Thank you for sharing this information freely and openly. 

A few feature requests that would be helpful: - 

1. Can you provide details on how to implement a paper trading environment similar to FinRL and Alpaca? This would be very helpful, allowing the testing of model on live trading data. Similar to:

https://github.com/AI4Finance-Foundation/FinRL/blob/master/examples/FinRL_PaperTrading_Demo.ipynb

2. Tutorials for integrating PRUDEX-Compass into TradeMaster and more reporting and logging of the DRL agent's actions/steps. Many of the reports output the return/sharpe ratio, but not easy to find details, csv, report on the trades, portfolio allocations (buys and sells, etc). Again, this would be useful to understand deeper into the best model and it's behavior and further optimization in different market conditions and asset types.

**Comment by XiaHaochong98** [comment]
Thank you for you interest in TradeMaster. These two features are indeed important and they are on our next-steps in developing TradeMaster.

1. The paper trading environment(which we call Sandbox) is now under development, we are building a simulator environment for our agents based on ABIDES and ABIDES-gym. We are developming the ABIDES so that it could learn from histrocial data beyond just replaying the markets for greater fidelity. This sub-project is the Section 4.2 of the [Sandbox Whitepaper](https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/docs/source/tool/TradeMaster_Sandbox_whitepaper.pdf). We will release it and add it to TradeMaster pipeline once we are done.
2.  The PRUDEX-Compass is for the benchmarking of large-scale experiments. We did not intergated it to the current TradeMaster pipeline and we may do it in the future. 
      As for the result analyzation, we only out put the most well-established metrics for cleaness as the need for analyzation varies. Acutally we do have detailed results recorded in .csv, .npy outputed with the experiments.  If you want further details about how the agent acts, you may play with the envrionments scripts and log more outputs.
      We have a dashboard visulizating all the tradining behavious of the agents along with the market, it will be incrooperated into TradeMaster in near future.
      Evaluation of the 'best model' is indeed a complex task. We are also working on this with new agents/pipelines under extensive experiments. They will be realsed in the future. A simple tool we are providing in TradeMaster is the 'dynamics_test' as described in this [doc](https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/docs/source/tool/EvaluationSandbox_MDM.md). 

If you have any further thoughts or suggestions, please feel free to contact us
