### ISSUE TITLE
How to define num_action for new trade type?

### ISSUE THREAD

**Issue by ztwe** [TradeMaster-NTU/TradeMaster#166]
If I train the model for new trade type, for example, Japanese Stock or London Future, how to define num_action?

**Comment by qinmoelei** [comment]
Hi,
If you are referring to the task portfolio management, the ideal solution is the number of portfolios in the pool plus 1.
The num_action indicates the number of dimensions of your action in portfolio management. In our trading environment, the action will first go through a softmax and transform itself from action to each portfolio weights. The reason to plus 1 is to add a riskless asset, saying cash, to the portfolio weights to make the simulation more realistic.

**Comment by ztwe** [comment]
@qinmoelei @DVampire @EC2EZ4RD 
Maybe  my expression is not clear enough.

I mean what value should assigned to num_action when train the model for new trade type.
Is the action means BUY OPEN, SELL OPEN, BUY CLOSE, SELL CLOSE, VOLUME and so on when the trade type is future?

**Comment by qinmoelei** [comment]
Sorry for the late reply,
I am still confused about your expression. Could you specify the config file, algorithms, environment and task you are referring?

**Comment by qinmoelei** [comment]
> @qinmoelei @DVampire @EC2EZ4RD Maybe my expression is not clear enough.
> 
> I mean what value should assigned to num_action when train the model for new trade type. Is the action means BUY OPEN, SELL OPEN, BUY CLOSE, SELL CLOSE, VOLUME and so on when the trade type is future?

If you are referring to high frequency trading environment, the process is as followed.
For high frequency trading environment, you need to have the snapshot of limit order book of your new trade type. The reason for that is during high frequency trading, transaction accuracy is the key. You can only conduct the order if there is enough liquidity in the market (saying, if you want to buy 0.01BTC right away, you have to check whether someone else in the market want to sell it in the limit order book, if there is no one want to sell it. Then your order could not be fully executed). The price per unit of the executed order is also determined by your order size. (Saying if you want to 1 BTC, there is a person want to sell 0.2 BTC at 25000/BTC and another person want to sell 0.8 BTC at 26000/BTC, you overall are paying (0.2*25000+0.8*26000)/(0.2+0.8))/BTC for one single BTC, but if you are only buying 0.2 BTC, then the price should be 25000/BTC.
Back to you question, under this trading scenario, the action itself only represents the position you want to hold currently, and the price is automatically calculated by the limit order book. Since each broker has regulation about the minimum volume for each order. We design the num_action to regulate the number of positions we are allowed to hold. This parameter with the parameter max_holding_number all together form the trading volume of your order.

For instance, if the max_holding_number  is 0.01 and the num_action is 5. It means the allowed positions are [0, 0.0025,0.005,0.0075,0.01], indicating the minimum volume for an order is 0.0025.

Therefore, the action does not mean BUY OPEN, SELL OPEN, BUY CLOSE, SELL CLOSE but just the position you want to hold currently.

Hope this answer your question, and please star and fork our repo, your support is very important for us.

**Comment by ztwe** [comment]
Thank you very much for your patient reply!

Now I know the meaning of this variable.

I have forked your repo and I am exploring this excellent project.

**Comment by ztwe** [comment]
@qinmoelei 

 Where do the operations define, such as BUY OPEN, SELL OPEN, BUY CLOSE, SELL CLOSE?

**Comment by qinmoelei** [comment]
Since it is in high frequency trading, there is no such operations as BUY OPEN, SELL OPEN, BUY CLOSE, SELL CLOSE because we are taking market order and the price for conducting the order is determined by the current limit order book instead of your choice of operation. This sort of operations could be found in portfolio management task, where all the settlements of all assets are close prices. So, the operation is limited in BUY CLOSE, SELL CLOSE.

**Comment by ztwe** [comment]
@qinmoelei 
"So, the operation is limited in BUY CLOSE, SELL CLOSE"
Is that wrong? Without OPEN operation, there is no position. Then CLOSE operation is Meaningless.

**Comment by qinmoelei** [comment]
Sorry for the late reply. 
In portfolio management, when we calculate the net value of our asset, we have to use a value to measure. Here we use close. The open and close price indicates the executed price for first trade and the last trade. They are determined by the data. By using close to measure our net curve, our assumption is that at the end of the day, we check our asset value and compare it with the last day's net curve and get my reward. Then based on the today's price information, we adjust our portfolio weights immediately before the market close and wait for another day coming and repeat this process over and over again before the dataset runs out.
