### ISSUE TITLE
MIssing file 'data/algorithmic_trading/AAPL/test_labeled_3_24_-0.05_0.05.csv'

### ISSUE THREAD

**Issue by JackXueIndiana** [TradeMaster-NTU/TradeMaster#181]
Can not find this file in repo: 'data/algorithmic_trading/AAPL/test_labeled_3_24_-0.05_0.05.csv'

**Comment by XiaHaochong98** [comment]
We've rolled out market dynamics testing datasets with the newest release of TradeMaster. These datasets are generated by our market dynamics modeling tool with scripts in https://github.com/TradeMaster-NTU/TradeMaster/tree/1.0.0/configs/market_dynamics_modeling. Please update your project to utilize the latest dataset. Training on AAPL data is currently in the experimental phase, please try out other supporting markets. Thank you for your interest in TradeMaster.

**Comment by JackXueIndiana** [comment]
Got it and thanks Haochong!

Thanks,
Jack

Jack Xue, Ph.D. & MBA | Principal Cloud Solution Architect for Application Innovation, Microsoft | USEC COGS CSU - Manufacturing |Desk: +1-425-421-7863, Cell: +1-317-993-1427

**Comment by JackXueIndiana** [comment]
Haochong,

Just want to confirm that in tutorials code examples we did not use LOB data as an input, right? Or I missed something?

Thanks,
Jack

Jack Xue, Ph.D. & MBA | Principal Cloud Solution Architect for Application Innovation, Microsoft | USEC COGS CSU - Manufacturing |Desk: +1-425-421-7863, Cell: +1-317-993-1427

From: Jack Xue
Sent: Wednesday, August 30, 2023 8:28 AM
To: ***@***.***; TradeMaster-NTU/TradeMaster ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [TradeMaster-NTU/TradeMaster] MIssing file 'data/algorithmic_trading/AAPL/test_labeled_3_24_-0.05_0.05.csv' (Issue #181)

Got it and thanks Haochong!

Thanks,
Jack

Jack Xue, Ph.D. & MBA | Principal Cloud Solution Architect for Application Innovation, Microsoft | USEC COGS CSU - Manufacturing |Desk: +1-425-421-7863, Cell: +1-317-993-1427

**Comment by XiaHaochong98** [comment]
Dear Jack,

For the most part of the TradeMaster project, we do not utilize LOB data and only focus on OHLCV because of data accessibility.

However, we do provide an example of HFT (https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/tools/high_frequency_trading/train.py) with LOB data (https://github.com/TradeMaster-NTU/TradeMaster/tree/1.0.0/data/high_frequency_trading/small_BTC), as a very primal example of our ongoing research using RL for HFT which has just been submitted for AAAI for review.

Yours,
Haochong Xia
________________________________
发件人: Jack Xue, Ph.D. ***@***.***>
发送时间: 2023年9月6日 0:53
收件人: TradeMaster-NTU/TradeMaster ***@***.***>
抄送: #XIA HAOCHONG# ***@***.***>; Comment ***@***.***>
主题: Re: [TradeMaster-NTU/TradeMaster] MIssing file 'data/algorithmic_trading/AAPL/test_labeled_3_24_-0.05_0.05.csv' (Issue #181)


Haochong,

Just want to confirm that in tutorials code examples we did not use LOB data as an input, right? Or I missed something?

Thanks,
Jack

Jack Xue, Ph.D. & MBA | Principal Cloud Solution Architect for Application Innovation, Microsoft | USEC COGS CSU - Manufacturing |Desk: +1-425-421-7863, Cell: +1-317-993-1427

From: Jack Xue
Sent: Wednesday, August 30, 2023 8:28 AM
To: ***@***.***; TradeMaster-NTU/TradeMaster ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [TradeMaster-NTU/TradeMaster] MIssing file 'data/algorithmic_trading/AAPL/test_labeled_3_24_-0.05_0.05.csv' (Issue #181)

Got it and thanks Haochong!

Thanks,
Jack

Jack Xue, Ph.D. & MBA | Principal Cloud Solution Architect for Application Innovation, Microsoft | USEC COGS CSU - Manufacturing |Desk: +1-425-421-7863, Cell: +1-317-993-1427
